server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.10.100
    port: 6379
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
