spring:
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.100:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    alicloud:
      access-key: #osskey
      secret-key: #osssecret
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

  application:
    name: gulimall-product-service

mybatis-plus:
  # mapper.xml配置文件地址
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置全局属性
  global-config:
    db-config:
      # id自增
      id-type: auto
      # 逻辑删除,0:隐藏,1:显示
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10001

logging:
  level:
    com.arccc.gulimall: DEBUG
