server:
  port: 12000
spring:
  application:
    name: gulimall-search-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.100:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.100
  session:
    store-type: redis
